print('hi' > 'hello' and 'bye' < 'Bye')
print('hi' > 'hello' or 'bye' < 'Bye')
print(7 > 8 or 5 < 6 and 'I am fine' > 'I am not fine')
print(10 !=9 and 29 >= 29)
print(10 !=9 and 29 >= 29 and 'hi' > 'hello' or 'bye' < 'Bye' and 7 <= 2.5)